### ISSUE TITLE
Unzipped images cannot be opened

### ISSUE THREAD

**Issue by eighteenlin** [CAMMA-public/Endoscapes#1]
Except for the images of train, val and test, the rest of the dataset cannot be opened normally, and the display does not support the format.

**Comment by adit98** [comment]
Hi, I am unable to reproduce the issue. Could you please provide more details (application used to open images, operating system, etc.)? Note that all images outside of the `train`, `val`, and `test` subsets are symbolic links, which could be causing the issue.

**Comment by eighteenlin** [comment]
Thank you for replying to my issue. When I was creating symbolic links, I couldn't find copy_images.py

create symlinks
python copy_images.py

heartily thank you in advance

**Comment by adit98** [comment]
There is no such script. The symlinks are already created in the zip folder.

**Comment by adit98** [comment]
Closing issue as it seems resolved.
