### ISSUE TITLE
Consistency between bounding box and CVS annotations

### ISSUE THREAD

**Issue by liyunfan13** [CAMMA-public/Endoscapes#10]
Hi,

I'm not sure if I'm understanding it right, but when working with the dataset, I can't help but notice that the binary labels for CVS aren't always consistent with the bounding boxes (when present). 
For instance, in frames where C3 are labeled as positive, sometimes we don't get both bounding boxes for cystic artery and cystic duct, and vice versa. Here I'm interpreting the C3 condition literally according to [SAGES](https://www.sages.org/safe-cholecystectomy-program/).
Was this sort of constraint a reasonable assumption with Endoscapes? Or do the bounding boxes and CVS annotations don't necessarily have to be aligned? Thanks!

**Comment by adit98** [comment]
Hi,

Please note that the definitions of C1, C2, and C3 in our work vary from the SAGES website - this is reflected in all of our publications. Part of the reason for this is that we formalize CVS achievement at the frame level in addition to the video-level, calling for an updated annotation protocol (https://arxiv.org/abs/2106.10916).

We define them as follows:
C1 - Two Structures Entering Gallbladder
C2 - Hepatocystic Triangle Dissection
C3 - Exposure of Cystic Plate

Apologies for the confusion!
