### ISSUE TITLE
Issue with the number of CVS201 Train frames 

### ISSUE THREAD

**Issue by franeknowak** [CAMMA-public/Endoscapes#4]
Hi again, I noticed that there might be a typo with the number of annotated frames in Endoscapes-CVS201. On page 3, Table 1 of the technical report, in the first row it states that there are 6970 annotations in Train subset for CVS (Binary Multilabel). I checked the dataset and it seems there are 6960, which is likely true given that otherwise all the frames don't add up to the reported 11090. Would it be possible to confirm if that is the case? Thank you!

**Comment by adit98** [comment]
Hi, yes you are correct, there is a typo in the technical report. Will update it shortly with the correct number (6960 labeled train images).

Thanks!
