### ISSUE TITLE
Segmentation mask value '255'

### ISSUE THREAD

**Issue by franeknowak** [CAMMA-public/Endoscapes#5]
Good afternoon,
Would it be possible to clarify the segmentation mask notation? To my understanding from documentation:

'label': segmentation value

'background': 0,
'cystic_plate': 1,
'calot_triangle': 2,
'cystic_artery': 3,
'cystic_duct': 4,
'gallbladder': 5,
'tool': 6,
'?': 255

What class has a mask value of 255?
Thank you

**Comment by adit98** [comment]
Hi,

The 255 label indicates uncertainty, or in other words, pixels that should be ignored during training/testing. This is quite standard in semantic segmentation. Note that these ignored instances are not part of the instance segmentation annotations.

**Comment by franeknowak** [comment]
Great, thank you!
