### ISSUE TITLE
The counts tag in annotation_coco.json

### ISSUE THREAD

**Issue by js66y** [CAMMA-public/Endoscapes#9]
The segmentation labels in COCO format are in the form of x and y coordinates. 
The content of the annotation_coco.json file is similar to: `dfk61n>2M3N101O1O001O001O1O001O000000001O000000001O0000001O01O001O01OO2O1O1O1O1O1O001O1O001O1O001O1O001OQUm4`
How should it be used? 
Thank you!

**Comment by adit98** [comment]
Hi,

The segmentation masks in the annotation files are RLE-encoded following the standard COCO format. You can use the [pycocotools package](https://pypi.org/project/pycocotools/) to decode these masks.

We also release the semantic segmentation masks as standard PNG images in the `semseg` folder.

Hope this helps!
